// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DiscussionsDiscussionIdCommentsCommentIdDeleteParams is parameters of DELETE /discussions/{discussionId}/comments/{commentId} operation.
type DiscussionsDiscussionIdCommentsCommentIdDeleteParams struct {
	DiscussionId ID
	CommentId    ID
}

func unpackDiscussionsDiscussionIdCommentsCommentIdDeleteParams(packed middleware.Parameters) (params DiscussionsDiscussionIdCommentsCommentIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "discussionId",
			In:   "path",
		}
		params.DiscussionId = packed[key].(ID)
	}
	{
		key := middleware.ParameterKey{
			Name: "commentId",
			In:   "path",
		}
		params.CommentId = packed[key].(ID)
	}
	return params
}

func decodeDiscussionsDiscussionIdCommentsCommentIdDeleteParams(args [2]string, argsEscaped bool, r *http.Request) (params DiscussionsDiscussionIdCommentsCommentIdDeleteParams, _ error) {
	// Decode path: discussionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "discussionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotDiscussionIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscussionIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DiscussionId = ID(paramsDotDiscussionIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DiscussionId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discussionId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: commentId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "commentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotCommentIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCommentIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CommentId = ID(paramsDotCommentIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.CommentId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "commentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DiscussionsDiscussionIdCommentsCommentIdPutParams is parameters of PUT /discussions/{discussionId}/comments/{commentId} operation.
type DiscussionsDiscussionIdCommentsCommentIdPutParams struct {
	DiscussionId ID
	CommentId    ID
}

func unpackDiscussionsDiscussionIdCommentsCommentIdPutParams(packed middleware.Parameters) (params DiscussionsDiscussionIdCommentsCommentIdPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "discussionId",
			In:   "path",
		}
		params.DiscussionId = packed[key].(ID)
	}
	{
		key := middleware.ParameterKey{
			Name: "commentId",
			In:   "path",
		}
		params.CommentId = packed[key].(ID)
	}
	return params
}

func decodeDiscussionsDiscussionIdCommentsCommentIdPutParams(args [2]string, argsEscaped bool, r *http.Request) (params DiscussionsDiscussionIdCommentsCommentIdPutParams, _ error) {
	// Decode path: discussionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "discussionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotDiscussionIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscussionIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DiscussionId = ID(paramsDotDiscussionIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DiscussionId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discussionId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: commentId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "commentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotCommentIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCommentIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CommentId = ID(paramsDotCommentIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.CommentId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "commentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DiscussionsDiscussionIdCommentsGetParams is parameters of GET /discussions/{discussionId}/comments operation.
type DiscussionsDiscussionIdCommentsGetParams struct {
	DiscussionId ID
}

func unpackDiscussionsDiscussionIdCommentsGetParams(packed middleware.Parameters) (params DiscussionsDiscussionIdCommentsGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "discussionId",
			In:   "path",
		}
		params.DiscussionId = packed[key].(ID)
	}
	return params
}

func decodeDiscussionsDiscussionIdCommentsGetParams(args [1]string, argsEscaped bool, r *http.Request) (params DiscussionsDiscussionIdCommentsGetParams, _ error) {
	// Decode path: discussionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "discussionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotDiscussionIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscussionIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DiscussionId = ID(paramsDotDiscussionIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DiscussionId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discussionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DiscussionsDiscussionIdCommentsPostParams is parameters of POST /discussions/{discussionId}/comments operation.
type DiscussionsDiscussionIdCommentsPostParams struct {
	DiscussionId ID
}

func unpackDiscussionsDiscussionIdCommentsPostParams(packed middleware.Parameters) (params DiscussionsDiscussionIdCommentsPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "discussionId",
			In:   "path",
		}
		params.DiscussionId = packed[key].(ID)
	}
	return params
}

func decodeDiscussionsDiscussionIdCommentsPostParams(args [1]string, argsEscaped bool, r *http.Request) (params DiscussionsDiscussionIdCommentsPostParams, _ error) {
	// Decode path: discussionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "discussionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotDiscussionIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscussionIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DiscussionId = ID(paramsDotDiscussionIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DiscussionId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discussionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DiscussionsDiscussionIdDeleteParams is parameters of DELETE /discussions/{discussionId} operation.
type DiscussionsDiscussionIdDeleteParams struct {
	DiscussionId ID
}

func unpackDiscussionsDiscussionIdDeleteParams(packed middleware.Parameters) (params DiscussionsDiscussionIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "discussionId",
			In:   "path",
		}
		params.DiscussionId = packed[key].(ID)
	}
	return params
}

func decodeDiscussionsDiscussionIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params DiscussionsDiscussionIdDeleteParams, _ error) {
	// Decode path: discussionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "discussionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotDiscussionIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscussionIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DiscussionId = ID(paramsDotDiscussionIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DiscussionId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discussionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DiscussionsDiscussionIdGetParams is parameters of GET /discussions/{discussionId} operation.
type DiscussionsDiscussionIdGetParams struct {
	DiscussionId ID
}

func unpackDiscussionsDiscussionIdGetParams(packed middleware.Parameters) (params DiscussionsDiscussionIdGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "discussionId",
			In:   "path",
		}
		params.DiscussionId = packed[key].(ID)
	}
	return params
}

func decodeDiscussionsDiscussionIdGetParams(args [1]string, argsEscaped bool, r *http.Request) (params DiscussionsDiscussionIdGetParams, _ error) {
	// Decode path: discussionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "discussionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotDiscussionIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscussionIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DiscussionId = ID(paramsDotDiscussionIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DiscussionId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discussionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DiscussionsDiscussionIdPutParams is parameters of PUT /discussions/{discussionId} operation.
type DiscussionsDiscussionIdPutParams struct {
	DiscussionId ID
}

func unpackDiscussionsDiscussionIdPutParams(packed middleware.Parameters) (params DiscussionsDiscussionIdPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "discussionId",
			In:   "path",
		}
		params.DiscussionId = packed[key].(ID)
	}
	return params
}

func decodeDiscussionsDiscussionIdPutParams(args [1]string, argsEscaped bool, r *http.Request) (params DiscussionsDiscussionIdPutParams, _ error) {
	// Decode path: discussionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "discussionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotDiscussionIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscussionIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DiscussionId = ID(paramsDotDiscussionIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DiscussionId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discussionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DiscussionsGetParams is parameters of GET /discussions operation.
type DiscussionsGetParams struct {
	ProjectId OptID `json:",omitempty,omitzero"`
}

func unpackDiscussionsGetParams(packed middleware.Parameters) (params DiscussionsGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "projectId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ProjectId = v.(OptID)
		}
	}
	return params
}

func decodeDiscussionsGetParams(args [0]string, argsEscaped bool, r *http.Request) (params DiscussionsGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: projectId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "projectId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotProjectIdVal ID
				if err := func() error {
					var paramsDotProjectIdValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotProjectIdValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotProjectIdVal = ID(paramsDotProjectIdValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.ProjectId.SetTo(paramsDotProjectIdVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ProjectId.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "projectId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ProjectsProjectIdDeleteParams is parameters of DELETE /projects/{projectId} operation.
type ProjectsProjectIdDeleteParams struct {
	ProjectId ID
}

func unpackProjectsProjectIdDeleteParams(packed middleware.Parameters) (params ProjectsProjectIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "projectId",
			In:   "path",
		}
		params.ProjectId = packed[key].(ID)
	}
	return params
}

func decodeProjectsProjectIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params ProjectsProjectIdDeleteParams, _ error) {
	// Decode path: projectId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "projectId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotProjectIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotProjectIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ProjectId = ID(paramsDotProjectIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.ProjectId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "projectId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ProjectsProjectIdGetParams is parameters of GET /projects/{projectId} operation.
type ProjectsProjectIdGetParams struct {
	ProjectId ID
}

func unpackProjectsProjectIdGetParams(packed middleware.Parameters) (params ProjectsProjectIdGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "projectId",
			In:   "path",
		}
		params.ProjectId = packed[key].(ID)
	}
	return params
}

func decodeProjectsProjectIdGetParams(args [1]string, argsEscaped bool, r *http.Request) (params ProjectsProjectIdGetParams, _ error) {
	// Decode path: projectId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "projectId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotProjectIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotProjectIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ProjectId = ID(paramsDotProjectIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.ProjectId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "projectId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ProjectsProjectIdPutParams is parameters of PUT /projects/{projectId} operation.
type ProjectsProjectIdPutParams struct {
	ProjectId ID
}

func unpackProjectsProjectIdPutParams(packed middleware.Parameters) (params ProjectsProjectIdPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "projectId",
			In:   "path",
		}
		params.ProjectId = packed[key].(ID)
	}
	return params
}

func decodeProjectsProjectIdPutParams(args [1]string, argsEscaped bool, r *http.Request) (params ProjectsProjectIdPutParams, _ error) {
	// Decode path: projectId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "projectId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotProjectIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotProjectIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ProjectId = ID(paramsDotProjectIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.ProjectId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "projectId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RulesRuleIdDeleteParams is parameters of DELETE /rules/{ruleId} operation.
type RulesRuleIdDeleteParams struct {
	RuleId ID
}

func unpackRulesRuleIdDeleteParams(packed middleware.Parameters) (params RulesRuleIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "ruleId",
			In:   "path",
		}
		params.RuleId = packed[key].(ID)
	}
	return params
}

func decodeRulesRuleIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params RulesRuleIdDeleteParams, _ error) {
	// Decode path: ruleId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ruleId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotRuleIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRuleIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.RuleId = ID(paramsDotRuleIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.RuleId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ruleId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RulesRuleIdGetParams is parameters of GET /rules/{ruleId} operation.
type RulesRuleIdGetParams struct {
	RuleId ID
}

func unpackRulesRuleIdGetParams(packed middleware.Parameters) (params RulesRuleIdGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "ruleId",
			In:   "path",
		}
		params.RuleId = packed[key].(ID)
	}
	return params
}

func decodeRulesRuleIdGetParams(args [1]string, argsEscaped bool, r *http.Request) (params RulesRuleIdGetParams, _ error) {
	// Decode path: ruleId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ruleId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotRuleIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRuleIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.RuleId = ID(paramsDotRuleIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.RuleId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ruleId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RulesRuleIdPutParams is parameters of PUT /rules/{ruleId} operation.
type RulesRuleIdPutParams struct {
	RuleId ID
}

func unpackRulesRuleIdPutParams(packed middleware.Parameters) (params RulesRuleIdPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "ruleId",
			In:   "path",
		}
		params.RuleId = packed[key].(ID)
	}
	return params
}

func decodeRulesRuleIdPutParams(args [1]string, argsEscaped bool, r *http.Request) (params RulesRuleIdPutParams, _ error) {
	// Decode path: ruleId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ruleId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotRuleIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRuleIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.RuleId = ID(paramsDotRuleIdVal)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.RuleId.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ruleId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
