//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Discussions = newDiscussionsTable("app-supportocol", "discussions", "")

type discussionsTable struct {
	mysql.Table

	// Columns
	ID                     mysql.ColumnString
	Theme                  mysql.ColumnString
	Background             mysql.ColumnString
	Conclusion             mysql.ColumnString
	RuleID                 mysql.ColumnString
	VisibilityLevel        mysql.ColumnString
	CommentPermissionLevel mysql.ColumnString
	CreatedBy              mysql.ColumnString
	CreatedAt              mysql.ColumnTimestamp
	UpdatedAt              mysql.ColumnTimestamp
	Status                 mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type DiscussionsTable struct {
	discussionsTable

	NEW discussionsTable
}

// AS creates new DiscussionsTable with assigned alias
func (a DiscussionsTable) AS(alias string) *DiscussionsTable {
	return newDiscussionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DiscussionsTable with assigned schema name
func (a DiscussionsTable) FromSchema(schemaName string) *DiscussionsTable {
	return newDiscussionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DiscussionsTable with assigned table prefix
func (a DiscussionsTable) WithPrefix(prefix string) *DiscussionsTable {
	return newDiscussionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DiscussionsTable with assigned table suffix
func (a DiscussionsTable) WithSuffix(suffix string) *DiscussionsTable {
	return newDiscussionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDiscussionsTable(schemaName, tableName, alias string) *DiscussionsTable {
	return &DiscussionsTable{
		discussionsTable: newDiscussionsTableImpl(schemaName, tableName, alias),
		NEW:              newDiscussionsTableImpl("", "new", ""),
	}
}

func newDiscussionsTableImpl(schemaName, tableName, alias string) discussionsTable {
	var (
		IDColumn                     = mysql.StringColumn("id")
		ThemeColumn                  = mysql.StringColumn("theme")
		BackgroundColumn             = mysql.StringColumn("background")
		ConclusionColumn             = mysql.StringColumn("conclusion")
		RuleIDColumn                 = mysql.StringColumn("rule_id")
		VisibilityLevelColumn        = mysql.StringColumn("visibility_level")
		CommentPermissionLevelColumn = mysql.StringColumn("comment_permission_level")
		CreatedByColumn              = mysql.StringColumn("created_by")
		CreatedAtColumn              = mysql.TimestampColumn("created_at")
		UpdatedAtColumn              = mysql.TimestampColumn("updated_at")
		StatusColumn                 = mysql.StringColumn("status")
		allColumns                   = mysql.ColumnList{IDColumn, ThemeColumn, BackgroundColumn, ConclusionColumn, RuleIDColumn, VisibilityLevelColumn, CommentPermissionLevelColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn, StatusColumn}
		mutableColumns               = mysql.ColumnList{ThemeColumn, BackgroundColumn, ConclusionColumn, RuleIDColumn, VisibilityLevelColumn, CommentPermissionLevelColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn, StatusColumn}
		defaultColumns               = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return discussionsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		Theme:                  ThemeColumn,
		Background:             BackgroundColumn,
		Conclusion:             ConclusionColumn,
		RuleID:                 RuleIDColumn,
		VisibilityLevel:        VisibilityLevelColumn,
		CommentPermissionLevel: CommentPermissionLevelColumn,
		CreatedBy:              CreatedByColumn,
		CreatedAt:              CreatedAtColumn,
		UpdatedAt:              UpdatedAtColumn,
		Status:                 StatusColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
