//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Comments = newCommentsTable("app-supportocol", "comments", "")

type commentsTable struct {
	mysql.Table

	// Columns
	ID              mysql.ColumnString
	DiscussionID    mysql.ColumnString
	ParentCommentID mysql.ColumnString
	CommentType     mysql.ColumnString
	Content         mysql.ColumnString
	PostedBy        mysql.ColumnString
	CreatedAt       mysql.ColumnTimestamp
	UpdatedAt       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type CommentsTable struct {
	commentsTable

	NEW commentsTable
}

// AS creates new CommentsTable with assigned alias
func (a CommentsTable) AS(alias string) *CommentsTable {
	return newCommentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CommentsTable with assigned schema name
func (a CommentsTable) FromSchema(schemaName string) *CommentsTable {
	return newCommentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CommentsTable with assigned table prefix
func (a CommentsTable) WithPrefix(prefix string) *CommentsTable {
	return newCommentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CommentsTable with assigned table suffix
func (a CommentsTable) WithSuffix(suffix string) *CommentsTable {
	return newCommentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCommentsTable(schemaName, tableName, alias string) *CommentsTable {
	return &CommentsTable{
		commentsTable: newCommentsTableImpl(schemaName, tableName, alias),
		NEW:           newCommentsTableImpl("", "new", ""),
	}
}

func newCommentsTableImpl(schemaName, tableName, alias string) commentsTable {
	var (
		IDColumn              = mysql.StringColumn("id")
		DiscussionIDColumn    = mysql.StringColumn("discussion_id")
		ParentCommentIDColumn = mysql.StringColumn("parent_comment_id")
		CommentTypeColumn     = mysql.StringColumn("comment_type")
		ContentColumn         = mysql.StringColumn("content")
		PostedByColumn        = mysql.StringColumn("posted_by")
		CreatedAtColumn       = mysql.TimestampColumn("created_at")
		UpdatedAtColumn       = mysql.TimestampColumn("updated_at")
		allColumns            = mysql.ColumnList{IDColumn, DiscussionIDColumn, ParentCommentIDColumn, CommentTypeColumn, ContentColumn, PostedByColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = mysql.ColumnList{DiscussionIDColumn, ParentCommentIDColumn, CommentTypeColumn, ContentColumn, PostedByColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return commentsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		DiscussionID:    DiscussionIDColumn,
		ParentCommentID: ParentCommentIDColumn,
		CommentType:     CommentTypeColumn,
		Content:         ContentColumn,
		PostedBy:        PostedByColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
