//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var CommentIssues = newCommentIssuesTable("app-supportocol", "comment_issues", "")

type commentIssuesTable struct {
	mysql.Table

	// Columns
	CommentID mysql.ColumnString
	IssueID   mysql.ColumnString
	Status    mysql.ColumnString
	CreatedBy mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type CommentIssuesTable struct {
	commentIssuesTable

	NEW commentIssuesTable
}

// AS creates new CommentIssuesTable with assigned alias
func (a CommentIssuesTable) AS(alias string) *CommentIssuesTable {
	return newCommentIssuesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CommentIssuesTable with assigned schema name
func (a CommentIssuesTable) FromSchema(schemaName string) *CommentIssuesTable {
	return newCommentIssuesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CommentIssuesTable with assigned table prefix
func (a CommentIssuesTable) WithPrefix(prefix string) *CommentIssuesTable {
	return newCommentIssuesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CommentIssuesTable with assigned table suffix
func (a CommentIssuesTable) WithSuffix(suffix string) *CommentIssuesTable {
	return newCommentIssuesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCommentIssuesTable(schemaName, tableName, alias string) *CommentIssuesTable {
	return &CommentIssuesTable{
		commentIssuesTable: newCommentIssuesTableImpl(schemaName, tableName, alias),
		NEW:                newCommentIssuesTableImpl("", "new", ""),
	}
}

func newCommentIssuesTableImpl(schemaName, tableName, alias string) commentIssuesTable {
	var (
		CommentIDColumn = mysql.StringColumn("comment_id")
		IssueIDColumn   = mysql.StringColumn("issue_id")
		StatusColumn    = mysql.StringColumn("status")
		CreatedByColumn = mysql.StringColumn("created_by")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
		allColumns      = mysql.ColumnList{CommentIDColumn, IssueIDColumn, StatusColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = mysql.ColumnList{StatusColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return commentIssuesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		CommentID: CommentIDColumn,
		IssueID:   IssueIDColumn,
		Status:    StatusColumn,
		CreatedBy: CreatedByColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
