// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	V1DialogueDiscussionsDiscussionIdCommentsGetOperation  OperationName = "V1DialogueDiscussionsDiscussionIdCommentsGet"
	V1DialogueDiscussionsDiscussionIdCommentsPostOperation OperationName = "V1DialogueDiscussionsDiscussionIdCommentsPost"
	V1DialogueDiscussionsDiscussionIdGetOperation          OperationName = "V1DialogueDiscussionsDiscussionIdGet"
	V1DialogueDiscussionsGetOperation                      OperationName = "V1DialogueDiscussionsGet"
)
