//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Comments struct {
	ID              string `sql:"primary_key"`
	DiscussionID    string
	ParentCommentID *string
	CommentType     string
	Content         string
	Status          string
	CreatedBy       string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
