//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CommentTypes struct {
	ID           string `sql:"primary_key"`
	DiscussionID string
	Name         string
	Description  *string
}
