//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Issues struct {
	ID          string `sql:"primary_key"`
	CommentID   string
	IssueType   string
	Description string
	CreatedBy   string
	CreatedAt   time.Time
}
