// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Comment
type Comment struct {
	ID              ID             `json:"id"`
	DiscussionId    ID             `json:"discussionId"`
	ParentCommentId NilID          `json:"parentCommentId"`
	CommentType     CommentType    `json:"commentType"`
	Content         CommentContent `json:"content"`
	Status          CommentStatus  `json:"status"`
	CreatedAt       time.Time      `json:"createdAt"`
	ArchivedAt      OptDateTime    `json:"archivedAt"`
}

// GetID returns the value of ID.
func (s *Comment) GetID() ID {
	return s.ID
}

// GetDiscussionId returns the value of DiscussionId.
func (s *Comment) GetDiscussionId() ID {
	return s.DiscussionId
}

// GetParentCommentId returns the value of ParentCommentId.
func (s *Comment) GetParentCommentId() NilID {
	return s.ParentCommentId
}

// GetCommentType returns the value of CommentType.
func (s *Comment) GetCommentType() CommentType {
	return s.CommentType
}

// GetContent returns the value of Content.
func (s *Comment) GetContent() CommentContent {
	return s.Content
}

// GetStatus returns the value of Status.
func (s *Comment) GetStatus() CommentStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Comment) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetArchivedAt returns the value of ArchivedAt.
func (s *Comment) GetArchivedAt() OptDateTime {
	return s.ArchivedAt
}

// SetID sets the value of ID.
func (s *Comment) SetID(val ID) {
	s.ID = val
}

// SetDiscussionId sets the value of DiscussionId.
func (s *Comment) SetDiscussionId(val ID) {
	s.DiscussionId = val
}

// SetParentCommentId sets the value of ParentCommentId.
func (s *Comment) SetParentCommentId(val NilID) {
	s.ParentCommentId = val
}

// SetCommentType sets the value of CommentType.
func (s *Comment) SetCommentType(val CommentType) {
	s.CommentType = val
}

// SetContent sets the value of Content.
func (s *Comment) SetContent(val CommentContent) {
	s.Content = val
}

// SetStatus sets the value of Status.
func (s *Comment) SetStatus(val CommentStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Comment) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetArchivedAt sets the value of ArchivedAt.
func (s *Comment) SetArchivedAt(val OptDateTime) {
	s.ArchivedAt = val
}

type CommentContent string

// Ref: #/components/schemas/CommentFrame
type CommentFrame struct {
	Types []CommentType `json:"types"`
	Paths []CommentPath `json:"paths"`
}

// GetTypes returns the value of Types.
func (s *CommentFrame) GetTypes() []CommentType {
	return s.Types
}

// GetPaths returns the value of Paths.
func (s *CommentFrame) GetPaths() []CommentPath {
	return s.Paths
}

// SetTypes sets the value of Types.
func (s *CommentFrame) SetTypes(val []CommentType) {
	s.Types = val
}

// SetPaths sets the value of Paths.
func (s *CommentFrame) SetPaths(val []CommentPath) {
	s.Paths = val
}

// Ref: #/components/schemas/CommentPath
type CommentPath struct {
	Child  CommentType `json:"child"`
	Parent CommentType `json:"parent"`
}

// GetChild returns the value of Child.
func (s *CommentPath) GetChild() CommentType {
	return s.Child
}

// GetParent returns the value of Parent.
func (s *CommentPath) GetParent() CommentType {
	return s.Parent
}

// SetChild sets the value of Child.
func (s *CommentPath) SetChild(val CommentType) {
	s.Child = val
}

// SetParent sets the value of Parent.
func (s *CommentPath) SetParent(val CommentType) {
	s.Parent = val
}

// Ref: #/components/schemas/CommentStatus
type CommentStatus string

const (
	CommentStatusActive   CommentStatus = "active"
	CommentStatusProposed CommentStatus = "proposed"
)

// AllValues returns all CommentStatus values.
func (CommentStatus) AllValues() []CommentStatus {
	return []CommentStatus{
		CommentStatusActive,
		CommentStatusProposed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CommentStatus) MarshalText() ([]byte, error) {
	switch s {
	case CommentStatusActive:
		return []byte(s), nil
	case CommentStatusProposed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CommentStatus) UnmarshalText(data []byte) error {
	switch CommentStatus(data) {
	case CommentStatusActive:
		*s = CommentStatusActive
		return nil
	case CommentStatusProposed:
		*s = CommentStatusProposed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CommentType string

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/DialogueSettings
type DialogueSettings struct {
	CommentFrame CommentFrame `json:"commentFrame"`
}

// GetCommentFrame returns the value of CommentFrame.
func (s *DialogueSettings) GetCommentFrame() CommentFrame {
	return s.CommentFrame
}

// SetCommentFrame sets the value of CommentFrame.
func (s *DialogueSettings) SetCommentFrame(val CommentFrame) {
	s.CommentFrame = val
}

// Ref: #/components/schemas/Discussion
type Discussion struct {
	ID               ID                   `json:"id"`
	Theme            DiscussionTheme      `json:"theme"`
	Conclusion       DiscussionConclusion `json:"conclusion"`
	Status           DiscussionStatus     `json:"status"`
	ArchivedAt       OptDateTime          `json:"archivedAt"`
	DialogueSettings OptDialogueSettings  `json:"dialogueSettings"`
}

// GetID returns the value of ID.
func (s *Discussion) GetID() ID {
	return s.ID
}

// GetTheme returns the value of Theme.
func (s *Discussion) GetTheme() DiscussionTheme {
	return s.Theme
}

// GetConclusion returns the value of Conclusion.
func (s *Discussion) GetConclusion() DiscussionConclusion {
	return s.Conclusion
}

// GetStatus returns the value of Status.
func (s *Discussion) GetStatus() DiscussionStatus {
	return s.Status
}

// GetArchivedAt returns the value of ArchivedAt.
func (s *Discussion) GetArchivedAt() OptDateTime {
	return s.ArchivedAt
}

// GetDialogueSettings returns the value of DialogueSettings.
func (s *Discussion) GetDialogueSettings() OptDialogueSettings {
	return s.DialogueSettings
}

// SetID sets the value of ID.
func (s *Discussion) SetID(val ID) {
	s.ID = val
}

// SetTheme sets the value of Theme.
func (s *Discussion) SetTheme(val DiscussionTheme) {
	s.Theme = val
}

// SetConclusion sets the value of Conclusion.
func (s *Discussion) SetConclusion(val DiscussionConclusion) {
	s.Conclusion = val
}

// SetStatus sets the value of Status.
func (s *Discussion) SetStatus(val DiscussionStatus) {
	s.Status = val
}

// SetArchivedAt sets the value of ArchivedAt.
func (s *Discussion) SetArchivedAt(val OptDateTime) {
	s.ArchivedAt = val
}

// SetDialogueSettings sets the value of DialogueSettings.
func (s *Discussion) SetDialogueSettings(val OptDialogueSettings) {
	s.DialogueSettings = val
}

type DiscussionConclusion string

// Ref: #/components/schemas/DiscussionStatus
type DiscussionStatus string

const (
	DiscussionStatusPrivate DiscussionStatus = "private"
	DiscussionStatusPublic  DiscussionStatus = "public"
)

// AllValues returns all DiscussionStatus values.
func (DiscussionStatus) AllValues() []DiscussionStatus {
	return []DiscussionStatus{
		DiscussionStatusPrivate,
		DiscussionStatusPublic,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DiscussionStatus) MarshalText() ([]byte, error) {
	switch s {
	case DiscussionStatusPrivate:
		return []byte(s), nil
	case DiscussionStatusPublic:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DiscussionStatus) UnmarshalText(data []byte) error {
	switch DiscussionStatus(data) {
	case DiscussionStatusPrivate:
		*s = DiscussionStatusPrivate
		return nil
	case DiscussionStatusPublic:
		*s = DiscussionStatusPublic
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/DiscussionSummary
type DiscussionSummary struct {
	ID              ID               `json:"id"`
	Theme           DiscussionTheme  `json:"theme"`
	Status          DiscussionStatus `json:"status"`
	ArchivedAt      OptDateTime      `json:"archivedAt"`
	LastCommentedAt time.Time        `json:"lastCommentedAt"`
}

// GetID returns the value of ID.
func (s *DiscussionSummary) GetID() ID {
	return s.ID
}

// GetTheme returns the value of Theme.
func (s *DiscussionSummary) GetTheme() DiscussionTheme {
	return s.Theme
}

// GetStatus returns the value of Status.
func (s *DiscussionSummary) GetStatus() DiscussionStatus {
	return s.Status
}

// GetArchivedAt returns the value of ArchivedAt.
func (s *DiscussionSummary) GetArchivedAt() OptDateTime {
	return s.ArchivedAt
}

// GetLastCommentedAt returns the value of LastCommentedAt.
func (s *DiscussionSummary) GetLastCommentedAt() time.Time {
	return s.LastCommentedAt
}

// SetID sets the value of ID.
func (s *DiscussionSummary) SetID(val ID) {
	s.ID = val
}

// SetTheme sets the value of Theme.
func (s *DiscussionSummary) SetTheme(val DiscussionTheme) {
	s.Theme = val
}

// SetStatus sets the value of Status.
func (s *DiscussionSummary) SetStatus(val DiscussionStatus) {
	s.Status = val
}

// SetArchivedAt sets the value of ArchivedAt.
func (s *DiscussionSummary) SetArchivedAt(val OptDateTime) {
	s.ArchivedAt = val
}

// SetLastCommentedAt sets the value of LastCommentedAt.
func (s *DiscussionSummary) SetLastCommentedAt(val time.Time) {
	s.LastCommentedAt = val
}

type DiscussionTheme string

// Ref: #/components/schemas/Error
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

type ID uuid.UUID

// LearningDiscussionsDiscussionIdCommentsCommentIdDeleteNoContent is response for LearningDiscussionsDiscussionIdCommentsCommentIdDelete operation.
type LearningDiscussionsDiscussionIdCommentsCommentIdDeleteNoContent struct{}

type LearningDiscussionsDiscussionIdCommentsCommentIdPutReq struct {
	CommentType CommentType    `json:"commentType"`
	Content     CommentContent `json:"content"`
}

// GetCommentType returns the value of CommentType.
func (s *LearningDiscussionsDiscussionIdCommentsCommentIdPutReq) GetCommentType() CommentType {
	return s.CommentType
}

// GetContent returns the value of Content.
func (s *LearningDiscussionsDiscussionIdCommentsCommentIdPutReq) GetContent() CommentContent {
	return s.Content
}

// SetCommentType sets the value of CommentType.
func (s *LearningDiscussionsDiscussionIdCommentsCommentIdPutReq) SetCommentType(val CommentType) {
	s.CommentType = val
}

// SetContent sets the value of Content.
func (s *LearningDiscussionsDiscussionIdCommentsCommentIdPutReq) SetContent(val CommentContent) {
	s.Content = val
}

type LearningDiscussionsDiscussionIdCommentsCommentIdStatusPutReq struct {
	Status CommentStatus `json:"status"`
}

// GetStatus returns the value of Status.
func (s *LearningDiscussionsDiscussionIdCommentsCommentIdStatusPutReq) GetStatus() CommentStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *LearningDiscussionsDiscussionIdCommentsCommentIdStatusPutReq) SetStatus(val CommentStatus) {
	s.Status = val
}

// LearningDiscussionsDiscussionIdCommentsGeneratePostAccepted is response for LearningDiscussionsDiscussionIdCommentsGeneratePost operation.
type LearningDiscussionsDiscussionIdCommentsGeneratePostAccepted struct{}

type LearningDiscussionsDiscussionIdCommentsGeneratePostReq struct {
	ParentCommentId NilID       `json:"parentCommentId"`
	CommentType     CommentType `json:"commentType"`
}

// GetParentCommentId returns the value of ParentCommentId.
func (s *LearningDiscussionsDiscussionIdCommentsGeneratePostReq) GetParentCommentId() NilID {
	return s.ParentCommentId
}

// GetCommentType returns the value of CommentType.
func (s *LearningDiscussionsDiscussionIdCommentsGeneratePostReq) GetCommentType() CommentType {
	return s.CommentType
}

// SetParentCommentId sets the value of ParentCommentId.
func (s *LearningDiscussionsDiscussionIdCommentsGeneratePostReq) SetParentCommentId(val NilID) {
	s.ParentCommentId = val
}

// SetCommentType sets the value of CommentType.
func (s *LearningDiscussionsDiscussionIdCommentsGeneratePostReq) SetCommentType(val CommentType) {
	s.CommentType = val
}

type LearningDiscussionsDiscussionIdCommentsPostReq struct {
	ParentCommentId NilID          `json:"parentCommentId"`
	CommentType     CommentType    `json:"commentType"`
	Content         CommentContent `json:"content"`
}

// GetParentCommentId returns the value of ParentCommentId.
func (s *LearningDiscussionsDiscussionIdCommentsPostReq) GetParentCommentId() NilID {
	return s.ParentCommentId
}

// GetCommentType returns the value of CommentType.
func (s *LearningDiscussionsDiscussionIdCommentsPostReq) GetCommentType() CommentType {
	return s.CommentType
}

// GetContent returns the value of Content.
func (s *LearningDiscussionsDiscussionIdCommentsPostReq) GetContent() CommentContent {
	return s.Content
}

// SetParentCommentId sets the value of ParentCommentId.
func (s *LearningDiscussionsDiscussionIdCommentsPostReq) SetParentCommentId(val NilID) {
	s.ParentCommentId = val
}

// SetCommentType sets the value of CommentType.
func (s *LearningDiscussionsDiscussionIdCommentsPostReq) SetCommentType(val CommentType) {
	s.CommentType = val
}

// SetContent sets the value of Content.
func (s *LearningDiscussionsDiscussionIdCommentsPostReq) SetContent(val CommentContent) {
	s.Content = val
}

// LearningDiscussionsDiscussionIdDeleteNoContent is response for LearningDiscussionsDiscussionIdDelete operation.
type LearningDiscussionsDiscussionIdDeleteNoContent struct{}

type LearningDiscussionsDiscussionIdPutReq struct {
	Theme      DiscussionTheme      `json:"theme"`
	Conclusion DiscussionConclusion `json:"conclusion"`
}

// GetTheme returns the value of Theme.
func (s *LearningDiscussionsDiscussionIdPutReq) GetTheme() DiscussionTheme {
	return s.Theme
}

// GetConclusion returns the value of Conclusion.
func (s *LearningDiscussionsDiscussionIdPutReq) GetConclusion() DiscussionConclusion {
	return s.Conclusion
}

// SetTheme sets the value of Theme.
func (s *LearningDiscussionsDiscussionIdPutReq) SetTheme(val DiscussionTheme) {
	s.Theme = val
}

// SetConclusion sets the value of Conclusion.
func (s *LearningDiscussionsDiscussionIdPutReq) SetConclusion(val DiscussionConclusion) {
	s.Conclusion = val
}

type LearningDiscussionsDiscussionIdStatusPutReq struct {
	Status       DiscussionStatus `json:"status"`
	CommentFrame OptCommentFrame  `json:"commentFrame"`
}

// GetStatus returns the value of Status.
func (s *LearningDiscussionsDiscussionIdStatusPutReq) GetStatus() DiscussionStatus {
	return s.Status
}

// GetCommentFrame returns the value of CommentFrame.
func (s *LearningDiscussionsDiscussionIdStatusPutReq) GetCommentFrame() OptCommentFrame {
	return s.CommentFrame
}

// SetStatus sets the value of Status.
func (s *LearningDiscussionsDiscussionIdStatusPutReq) SetStatus(val DiscussionStatus) {
	s.Status = val
}

// SetCommentFrame sets the value of CommentFrame.
func (s *LearningDiscussionsDiscussionIdStatusPutReq) SetCommentFrame(val OptCommentFrame) {
	s.CommentFrame = val
}

type LearningDiscussionsPostReq struct {
	Theme  DiscussionTheme  `json:"theme"`
	Status DiscussionStatus `json:"status"`
}

// GetTheme returns the value of Theme.
func (s *LearningDiscussionsPostReq) GetTheme() DiscussionTheme {
	return s.Theme
}

// GetStatus returns the value of Status.
func (s *LearningDiscussionsPostReq) GetStatus() DiscussionStatus {
	return s.Status
}

// SetTheme sets the value of Theme.
func (s *LearningDiscussionsPostReq) SetTheme(val DiscussionTheme) {
	s.Theme = val
}

// SetStatus sets the value of Status.
func (s *LearningDiscussionsPostReq) SetStatus(val DiscussionStatus) {
	s.Status = val
}

// NewNilID returns new NilID with value set to v.
func NewNilID(v ID) NilID {
	return NilID{
		Value: v,
	}
}

// NilID is nullable ID.
type NilID struct {
	Value ID
	Null  bool
}

// SetTo sets value to v.
func (o *NilID) SetTo(v ID) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilID) SetToNull() {
	o.Null = true
	var v ID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilID) Get() (v ID, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilID) Or(d ID) ID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCommentFrame returns new OptCommentFrame with value set to v.
func NewOptCommentFrame(v CommentFrame) OptCommentFrame {
	return OptCommentFrame{
		Value: v,
		Set:   true,
	}
}

// OptCommentFrame is optional CommentFrame.
type OptCommentFrame struct {
	Value CommentFrame
	Set   bool
}

// IsSet returns true if OptCommentFrame was set.
func (o OptCommentFrame) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCommentFrame) Reset() {
	var v CommentFrame
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCommentFrame) SetTo(v CommentFrame) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCommentFrame) Get() (v CommentFrame, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCommentFrame) Or(d CommentFrame) CommentFrame {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDialogueSettings returns new OptDialogueSettings with value set to v.
func NewOptDialogueSettings(v DialogueSettings) OptDialogueSettings {
	return OptDialogueSettings{
		Value: v,
		Set:   true,
	}
}

// OptDialogueSettings is optional DialogueSettings.
type OptDialogueSettings struct {
	Value DialogueSettings
	Set   bool
}

// IsSet returns true if OptDialogueSettings was set.
func (o OptDialogueSettings) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDialogueSettings) Reset() {
	var v DialogueSettings
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDialogueSettings) SetTo(v DialogueSettings) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDialogueSettings) Get() (v DialogueSettings, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDialogueSettings) Or(d DialogueSettings) DialogueSettings {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
