// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	LearningDiscussionsDiscussionIdCommentsCommentIdDeleteOperation    OperationName = "LearningDiscussionsDiscussionIdCommentsCommentIdDelete"
	LearningDiscussionsDiscussionIdCommentsCommentIdPutOperation       OperationName = "LearningDiscussionsDiscussionIdCommentsCommentIdPut"
	LearningDiscussionsDiscussionIdCommentsCommentIdStatusPutOperation OperationName = "LearningDiscussionsDiscussionIdCommentsCommentIdStatusPut"
	LearningDiscussionsDiscussionIdCommentsGeneratePostOperation       OperationName = "LearningDiscussionsDiscussionIdCommentsGeneratePost"
	LearningDiscussionsDiscussionIdCommentsGetOperation                OperationName = "LearningDiscussionsDiscussionIdCommentsGet"
	LearningDiscussionsDiscussionIdCommentsPostOperation               OperationName = "LearningDiscussionsDiscussionIdCommentsPost"
	LearningDiscussionsDiscussionIdDeleteOperation                     OperationName = "LearningDiscussionsDiscussionIdDelete"
	LearningDiscussionsDiscussionIdGetOperation                        OperationName = "LearningDiscussionsDiscussionIdGet"
	LearningDiscussionsDiscussionIdPutOperation                        OperationName = "LearningDiscussionsDiscussionIdPut"
	LearningDiscussionsGetOperation                                    OperationName = "LearningDiscussionsGet"
	LearningDiscussionsPostOperation                                   OperationName = "LearningDiscussionsPost"
)
