// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// LearningDiscussionsDiscussionIdArchiveDelete implements DELETE /learning/discussions/{discussionId}/archive operation.
//
// Unarchive discussion.
//
// DELETE /learning/discussions/{discussionId}/archive
func (UnimplementedHandler) LearningDiscussionsDiscussionIdArchiveDelete(ctx context.Context, params LearningDiscussionsDiscussionIdArchiveDeleteParams) (r *Discussion, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdArchivePost implements POST /learning/discussions/{discussionId}/archive operation.
//
// Archive discussion.
//
// POST /learning/discussions/{discussionId}/archive
func (UnimplementedHandler) LearningDiscussionsDiscussionIdArchivePost(ctx context.Context, params LearningDiscussionsDiscussionIdArchivePostParams) (r *Discussion, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdCommentsCommentIdDelete implements DELETE /learning/discussions/{discussionId}/comments/{commentId} operation.
//
// Delete comment.
//
// DELETE /learning/discussions/{discussionId}/comments/{commentId}
func (UnimplementedHandler) LearningDiscussionsDiscussionIdCommentsCommentIdDelete(ctx context.Context, params LearningDiscussionsDiscussionIdCommentsCommentIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdCommentsCommentIdPut implements PUT /learning/discussions/{discussionId}/comments/{commentId} operation.
//
// Update comment.
//
// PUT /learning/discussions/{discussionId}/comments/{commentId}
func (UnimplementedHandler) LearningDiscussionsDiscussionIdCommentsCommentIdPut(ctx context.Context, req *LearningDiscussionsDiscussionIdCommentsCommentIdPutReq, params LearningDiscussionsDiscussionIdCommentsCommentIdPutParams) (r *Comment, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdCommentsCommentIdStatusPut implements PUT /learning/discussions/{discussionId}/comments/{commentId}/status operation.
//
// Update comment status.
//
// PUT /learning/discussions/{discussionId}/comments/{commentId}/status
func (UnimplementedHandler) LearningDiscussionsDiscussionIdCommentsCommentIdStatusPut(ctx context.Context, req *LearningDiscussionsDiscussionIdCommentsCommentIdStatusPutReq, params LearningDiscussionsDiscussionIdCommentsCommentIdStatusPutParams) (r *Comment, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdCommentsGeneratePost implements POST /learning/discussions/{discussionId}/comments/generate operation.
//
// Generate comments using AI.
//
// POST /learning/discussions/{discussionId}/comments/generate
func (UnimplementedHandler) LearningDiscussionsDiscussionIdCommentsGeneratePost(ctx context.Context, req *LearningDiscussionsDiscussionIdCommentsGeneratePostReq, params LearningDiscussionsDiscussionIdCommentsGeneratePostParams) error {
	return ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdCommentsGet implements GET /learning/discussions/{discussionId}/comments operation.
//
// Get comments for a discussion.
//
// GET /learning/discussions/{discussionId}/comments
func (UnimplementedHandler) LearningDiscussionsDiscussionIdCommentsGet(ctx context.Context, params LearningDiscussionsDiscussionIdCommentsGetParams) (r []Comment, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdCommentsPost implements POST /learning/discussions/{discussionId}/comments operation.
//
// Create comment.
//
// POST /learning/discussions/{discussionId}/comments
func (UnimplementedHandler) LearningDiscussionsDiscussionIdCommentsPost(ctx context.Context, req *LearningDiscussionsDiscussionIdCommentsPostReq, params LearningDiscussionsDiscussionIdCommentsPostParams) (r *Comment, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdDelete implements DELETE /learning/discussions/{discussionId} operation.
//
// Delete discussion.
//
// DELETE /learning/discussions/{discussionId}
func (UnimplementedHandler) LearningDiscussionsDiscussionIdDelete(ctx context.Context, params LearningDiscussionsDiscussionIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdGet implements GET /learning/discussions/{discussionId} operation.
//
// Get discussion.
//
// GET /learning/discussions/{discussionId}
func (UnimplementedHandler) LearningDiscussionsDiscussionIdGet(ctx context.Context, params LearningDiscussionsDiscussionIdGetParams) (r *Discussion, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdPut implements PUT /learning/discussions/{discussionId} operation.
//
// Update discussion.
//
// PUT /learning/discussions/{discussionId}
func (UnimplementedHandler) LearningDiscussionsDiscussionIdPut(ctx context.Context, req *LearningDiscussionsDiscussionIdPutReq, params LearningDiscussionsDiscussionIdPutParams) (r *Discussion, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsDiscussionIdStatusPut implements PUT /learning/discussions/{discussionId}/status operation.
//
// Update discussion status.
//
// PUT /learning/discussions/{discussionId}/status
func (UnimplementedHandler) LearningDiscussionsDiscussionIdStatusPut(ctx context.Context, req *LearningDiscussionsDiscussionIdStatusPutReq, params LearningDiscussionsDiscussionIdStatusPutParams) (r *Discussion, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsGet implements GET /learning/discussions operation.
//
// Get discussions.
//
// GET /learning/discussions
func (UnimplementedHandler) LearningDiscussionsGet(ctx context.Context) (r []DiscussionSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// LearningDiscussionsPost implements POST /learning/discussions operation.
//
// Create discussion.
//
// POST /learning/discussions
func (UnimplementedHandler) LearningDiscussionsPost(ctx context.Context, req *LearningDiscussionsPostReq) (r *Discussion, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
