openapi: 3.1.0
info:
  title: app-supportocol learning api
  version: 1.0.0
components:
  securitySchemes:
    cookie_auth:
      type: apiKey
      in: cookie
      name: auth_token
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          minimum: 100
          maximum: 599
        message:
          type: string
      required:
        - code
        - message
    Id:
      type: string
      format: uuid
    CommentStatus:
      type: string
      enum:
        - active
        - proposed
    DialogueSettings:
      type: object
      properties:
        commentFrame:
          $ref: "#/components/schemas/CommentFrame"
      required:
        - commentFrame
    CommentFrame:
      type: object
      properties:
        types:
          type: array
          items:
            $ref: "#/components/schemas/CommentType"
        paths:
          type: array
          items:
            $ref: "#/components/schemas/CommentPath"
      required:
        - types
        - paths
    CommentPath:
      type: object
      properties:
        child:
          $ref: "#/components/schemas/CommentType"
        parent:
          $ref: "#/components/schemas/CommentType"
      required:
        - child
        - parent
    DiscussionStatus:
      type: string
      enum:
        - private
        - public
    DiscussionTheme:
      type: string
      maxLength: 255
    DiscussionConclusion:
      type: string
      maxLength: 1000
    CommentType:
      type: string
      maxLength: 20
    CommentContent:
      type: string
      maxLength: 400
    DiscussionSummary:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        theme:
          $ref: "#/components/schemas/DiscussionTheme"
        status:
          $ref: "#/components/schemas/DiscussionStatus"
        archivedAt:
          type: string
          format: date-time
        lastCommentedAt:
          type: string
          format: date-time
      required:
        - id
        - theme
        - status
        - lastCommentedAt
    Discussion:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        theme:
          $ref: "#/components/schemas/DiscussionTheme"
        conclusion:
          $ref: "#/components/schemas/DiscussionConclusion"
        status:
          $ref: "#/components/schemas/DiscussionStatus"
        archivedAt:
          type: string
          format: date-time
        dialogueSettings:
          $ref: "#/components/schemas/DialogueSettings"
      required:
        - id
        - theme
        - conclusion
        - status
    Comment:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        discussionId:
          $ref: "#/components/schemas/Id"
        parentCommentId:
          anyOf:
            - $ref: "#/components/schemas/Id"
            - type: "null"
        commentType:
          $ref: "#/components/schemas/CommentType"
        content:
          $ref: "#/components/schemas/CommentContent"
        status:
          $ref: "#/components/schemas/CommentStatus"
        createdAt:
          type: string
          format: date-time
        archivedAt:
          type: string
          format: date-time
      required:
        - id
        - discussionId
        - parentCommentId
        - commentType
        - content
        - status
        - createdAt
security:
  - cookie_auth: []
paths:
  /learning/discussions:
    get:
      description: get discussions
      parameters:
        - name: archived
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DiscussionSummary"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: create discussion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                theme:
                  $ref: "#/components/schemas/DiscussionTheme"
                status:
                  $ref: "#/components/schemas/DiscussionStatus"
              required:
                - theme
                - status
      responses:
        "201":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discussion"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}:
    get:
      description: get discussion
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discussion"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      description: update discussion
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                theme:
                  $ref: "#/components/schemas/DiscussionTheme"
                conclusion:
                  $ref: "#/components/schemas/DiscussionConclusion"
              required:
                - theme
                - conclusion
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discussion"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: delete discussion
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      responses:
        "204":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}/status:
    put:
      description: update discussion status
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: "#/components/schemas/DiscussionStatus"
                commentFrame:
                  $ref: "#/components/schemas/CommentFrame"
              required:
                - status
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discussion"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}/archive:
    post:
      description: archive discussion
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discussion"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: unarchive discussion
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discussion"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}/comments:
    get:
      description: get comments for a discussion
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
        - schema:
            type: string
            format: date-time
          required: false
          name: since
          in: query
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: create comment
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parentCommentId:
                  anyOf:
                    - $ref: "#/components/schemas/Id"
                    - type: "null"
                commentType:
                  $ref: "#/components/schemas/CommentType"
                content:
                  $ref: "#/components/schemas/CommentContent"
              required:
                - parentCommentId
                - commentType
                - content
      responses:
        "201":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}/comments/{commentId}:
    put:
      description: update comment
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: commentId
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentType:
                  $ref: "#/components/schemas/CommentType"
                content:
                  $ref: "#/components/schemas/CommentContent"
              required:
                - commentType
                - content
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: delete comment
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: commentId
          in: path
      responses:
        "204":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}/comments/{commentId}/status:
    put:
      description: update comment status
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: commentId
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: "#/components/schemas/CommentStatus"
              required:
                - status
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}/comments/{commentId}/archive:
    post:
      description: archive comment
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: commentId
          in: path
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: unarchive comment
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: commentId
          in: path
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /learning/discussions/{discussionId}/comments/generate:
    post:
      description: generate comments using AI
      parameters:
        - schema:
            $ref: "#/components/schemas/Id"
          required: true
          name: discussionId
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parentCommentId:
                  anyOf:
                    - $ref: "#/components/schemas/Id"
                    - type: "null"
                commentType:
                  $ref: "#/components/schemas/CommentType"
              required:
                - parentCommentId
                - commentType
      responses:
        "202":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
