// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	V1WorkspaceWorkspacesWorkspaceIdProjectsGetOperation             OperationName = "V1WorkspaceWorkspacesWorkspaceIdProjectsGet"
	V1WorkspaceWorkspacesWorkspaceIdProjectsPostOperation            OperationName = "V1WorkspaceWorkspacesWorkspaceIdProjectsPost"
	V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDeleteOperation OperationName = "V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDelete"
	V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdPutOperation    OperationName = "V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdPut"
)
