// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// V1WorkspaceMeGet implements GET /v1/workspace/me operation.
	//
	// Get my workspaces.
	//
	// GET /v1/workspace/me
	V1WorkspaceMeGet(ctx context.Context) ([]WorkspaceWithMember, error)
	// V1WorkspaceWorkspacesWorkspaceIdDiscussionsDiscussionIdFavoriteDelete implements DELETE /v1/workspace/workspaces/{workspaceId}/discussions/{discussionId}/favorite operation.
	//
	// Remove discussion from favorites.
	//
	// DELETE /v1/workspace/workspaces/{workspaceId}/discussions/{discussionId}/favorite
	V1WorkspaceWorkspacesWorkspaceIdDiscussionsDiscussionIdFavoriteDelete(ctx context.Context, params V1WorkspaceWorkspacesWorkspaceIdDiscussionsDiscussionIdFavoriteDeleteParams) error
	// V1WorkspaceWorkspacesWorkspaceIdDiscussionsDiscussionIdFavoritePut implements PUT /v1/workspace/workspaces/{workspaceId}/discussions/{discussionId}/favorite operation.
	//
	// Add discussion to favorites.
	//
	// PUT /v1/workspace/workspaces/{workspaceId}/discussions/{discussionId}/favorite
	V1WorkspaceWorkspacesWorkspaceIdDiscussionsDiscussionIdFavoritePut(ctx context.Context, params V1WorkspaceWorkspacesWorkspaceIdDiscussionsDiscussionIdFavoritePutParams) error
	// V1WorkspaceWorkspacesWorkspaceIdFavoritesGet implements GET /v1/workspace/workspaces/{workspaceId}/favorites operation.
	//
	// Get favorite discussions.
	//
	// GET /v1/workspace/workspaces/{workspaceId}/favorites
	V1WorkspaceWorkspacesWorkspaceIdFavoritesGet(ctx context.Context, params V1WorkspaceWorkspacesWorkspaceIdFavoritesGetParams) ([]FavoriteDiscussionSummary, error)
	// V1WorkspaceWorkspacesWorkspaceIdProjectsGet implements GET /v1/workspace/workspaces/{workspaceId}/projects operation.
	//
	// Get projects.
	//
	// GET /v1/workspace/workspaces/{workspaceId}/projects
	V1WorkspaceWorkspacesWorkspaceIdProjectsGet(ctx context.Context, params V1WorkspaceWorkspacesWorkspaceIdProjectsGetParams) ([]Project, error)
	// V1WorkspaceWorkspacesWorkspaceIdProjectsPost implements POST /v1/workspace/workspaces/{workspaceId}/projects operation.
	//
	// Create project.
	//
	// POST /v1/workspace/workspaces/{workspaceId}/projects
	V1WorkspaceWorkspacesWorkspaceIdProjectsPost(ctx context.Context, req *V1WorkspaceWorkspacesWorkspaceIdProjectsPostReq, params V1WorkspaceWorkspacesWorkspaceIdProjectsPostParams) (*Project, error)
	// V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDelete implements DELETE /v1/workspace/workspaces/{workspaceId}/projects/{projectId} operation.
	//
	// Delete project.
	//
	// DELETE /v1/workspace/workspaces/{workspaceId}/projects/{projectId}
	V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDelete(ctx context.Context, params V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDeleteParams) error
	// V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDiscussionsMovePost implements POST /v1/workspace/workspaces/{workspaceId}/projects/{projectId}/discussions/move operation.
	//
	// Move multiple discussions to a project.
	//
	// POST /v1/workspace/workspaces/{workspaceId}/projects/{projectId}/discussions/move
	V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDiscussionsMovePost(ctx context.Context, req *V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDiscussionsMovePostReq, params V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdDiscussionsMovePostParams) error
	// V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdPut implements PUT /v1/workspace/workspaces/{workspaceId}/projects/{projectId} operation.
	//
	// Update project.
	//
	// PUT /v1/workspace/workspaces/{workspaceId}/projects/{projectId}
	V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdPut(ctx context.Context, req *V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdPutReq, params V1WorkspaceWorkspacesWorkspaceIdProjectsProjectIdPutParams) (*Project, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
