// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// WorkspaceWorkspaceIdProjectsGet implements GET /workspace/{workspaceId}/projects operation.
	//
	// Get projects.
	//
	// GET /workspace/{workspaceId}/projects
	WorkspaceWorkspaceIdProjectsGet(ctx context.Context, params WorkspaceWorkspaceIdProjectsGetParams) ([]Project, error)
	// WorkspaceWorkspaceIdProjectsPost implements POST /workspace/{workspaceId}/projects operation.
	//
	// Create project.
	//
	// POST /workspace/{workspaceId}/projects
	WorkspaceWorkspaceIdProjectsPost(ctx context.Context, req *WorkspaceWorkspaceIdProjectsPostReq, params WorkspaceWorkspaceIdProjectsPostParams) (*Project, error)
	// WorkspaceWorkspaceIdProjectsProjectIdDelete implements DELETE /workspace/{workspaceId}/projects/{projectId} operation.
	//
	// Delete project.
	//
	// DELETE /workspace/{workspaceId}/projects/{projectId}
	WorkspaceWorkspaceIdProjectsProjectIdDelete(ctx context.Context, params WorkspaceWorkspaceIdProjectsProjectIdDeleteParams) error
	// WorkspaceWorkspaceIdProjectsProjectIdGet implements GET /workspace/{workspaceId}/projects/{projectId} operation.
	//
	// Get project.
	//
	// GET /workspace/{workspaceId}/projects/{projectId}
	WorkspaceWorkspaceIdProjectsProjectIdGet(ctx context.Context, params WorkspaceWorkspaceIdProjectsProjectIdGetParams) (*Project, error)
	// WorkspaceWorkspaceIdProjectsProjectIdPut implements PUT /workspace/{workspaceId}/projects/{projectId} operation.
	//
	// Update project.
	//
	// PUT /workspace/{workspaceId}/projects/{projectId}
	WorkspaceWorkspaceIdProjectsProjectIdPut(ctx context.Context, req *WorkspaceWorkspaceIdProjectsProjectIdPutReq, params WorkspaceWorkspaceIdProjectsProjectIdPutParams) (*Project, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
