// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	WorkspacesWorkspaceIdProjectsGetOperation             OperationName = "WorkspacesWorkspaceIdProjectsGet"
	WorkspacesWorkspaceIdProjectsPostOperation            OperationName = "WorkspacesWorkspaceIdProjectsPost"
	WorkspacesWorkspaceIdProjectsProjectIdDeleteOperation OperationName = "WorkspacesWorkspaceIdProjectsProjectIdDelete"
	WorkspacesWorkspaceIdProjectsProjectIdGetOperation    OperationName = "WorkspacesWorkspaceIdProjectsProjectIdGet"
	WorkspacesWorkspaceIdProjectsProjectIdPutOperation    OperationName = "WorkspacesWorkspaceIdProjectsProjectIdPut"
)
