openapi: 3.1.0
info:
  title: app-supportocol auth api
  version: 1.0.0
components:
  securitySchemes:
    cookie_auth:
      type: apiKey
      in: cookie
      name: auth_token
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          minimum: 100
          maximum: 599
        message:
          type: string
      required:
        - code
        - message
    GoogleLoginRequest:
      type: object
      properties:
        idToken:
          type: string
      required:
        - idToken
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
      required:
        - id
        - email
        - name
    SignupWithEmailRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    LoginWithEmailRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    VerifyEmailRequest:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    ResendVerifyEmailRequest:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
        - email
paths:
  /v1/identity/google:
    post:
      description: google login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GoogleLoginRequest"
      responses:
        "200":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/identity/logout:
    post:
      description: logout
      responses:
        "200":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/identity/me:
    get:
      description: get current user
      security:
        - cookie_auth: []
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: delete current user account
      security:
        - cookie_auth: []
      responses:
        "200":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/identity/errors:
    post:
      description: post an error
      security:
        - cookie_auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
      responses:
        "200":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/identity/signup:
    post:
      description: signup with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupWithEmailRequest"
      responses:
        "200":
          description: success response (email verification required)
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/identity/login:
    post:
      description: login with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginWithEmailRequest"
      responses:
        "200":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/identity/verify-email:
    post:
      description: verify email address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyEmailRequest"
      responses:
        "200":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/identity/resend-verify-email:
    post:
      description: resend verification email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResendVerifyEmailRequest"
      responses:
        "200":
          description: success response
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
