//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CommentTypePaths = newCommentTypePathsTable("public", "comment_type_paths", "")

type commentTypePathsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	DiscussionID      postgres.ColumnString
	FromCommentTypeID postgres.ColumnString
	ToCommentTypeID   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CommentTypePathsTable struct {
	commentTypePathsTable

	EXCLUDED commentTypePathsTable
}

// AS creates new CommentTypePathsTable with assigned alias
func (a CommentTypePathsTable) AS(alias string) *CommentTypePathsTable {
	return newCommentTypePathsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CommentTypePathsTable with assigned schema name
func (a CommentTypePathsTable) FromSchema(schemaName string) *CommentTypePathsTable {
	return newCommentTypePathsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CommentTypePathsTable with assigned table prefix
func (a CommentTypePathsTable) WithPrefix(prefix string) *CommentTypePathsTable {
	return newCommentTypePathsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CommentTypePathsTable with assigned table suffix
func (a CommentTypePathsTable) WithSuffix(suffix string) *CommentTypePathsTable {
	return newCommentTypePathsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCommentTypePathsTable(schemaName, tableName, alias string) *CommentTypePathsTable {
	return &CommentTypePathsTable{
		commentTypePathsTable: newCommentTypePathsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newCommentTypePathsTableImpl("", "excluded", ""),
	}
}

func newCommentTypePathsTableImpl(schemaName, tableName, alias string) commentTypePathsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		DiscussionIDColumn      = postgres.StringColumn("discussion_id")
		FromCommentTypeIDColumn = postgres.StringColumn("from_comment_type_id")
		ToCommentTypeIDColumn   = postgres.StringColumn("to_comment_type_id")
		allColumns              = postgres.ColumnList{IDColumn, DiscussionIDColumn, FromCommentTypeIDColumn, ToCommentTypeIDColumn}
		mutableColumns          = postgres.ColumnList{DiscussionIDColumn, FromCommentTypeIDColumn, ToCommentTypeIDColumn}
		defaultColumns          = postgres.ColumnList{}
	)

	return commentTypePathsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		DiscussionID:      DiscussionIDColumn,
		FromCommentTypeID: FromCommentTypeIDColumn,
		ToCommentTypeID:   ToCommentTypeIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
