//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Groups = newGroupsTable("public", "groups", "")

type groupsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	CreatedBy   postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type GroupsTable struct {
	groupsTable

	EXCLUDED groupsTable
}

// AS creates new GroupsTable with assigned alias
func (a GroupsTable) AS(alias string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupsTable with assigned schema name
func (a GroupsTable) FromSchema(schemaName string) *GroupsTable {
	return newGroupsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupsTable with assigned table prefix
func (a GroupsTable) WithPrefix(prefix string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupsTable with assigned table suffix
func (a GroupsTable) WithSuffix(suffix string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupsTable(schemaName, tableName, alias string) *GroupsTable {
	return &GroupsTable{
		groupsTable: newGroupsTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newGroupsTableImpl("", "excluded", ""),
	}
}

func newGroupsTableImpl(schemaName, tableName, alias string) groupsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedByColumn   = postgres.StringColumn("created_by")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, CreatedByColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, DescriptionColumn, CreatedByColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{CreatedAtColumn}
	)

	return groupsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		CreatedBy:   CreatedByColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
