//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Rules = newRulesTable("public", "rules", "")

type rulesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	CreatedBy   postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RulesTable struct {
	rulesTable

	EXCLUDED rulesTable
}

// AS creates new RulesTable with assigned alias
func (a RulesTable) AS(alias string) *RulesTable {
	return newRulesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RulesTable with assigned schema name
func (a RulesTable) FromSchema(schemaName string) *RulesTable {
	return newRulesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RulesTable with assigned table prefix
func (a RulesTable) WithPrefix(prefix string) *RulesTable {
	return newRulesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RulesTable with assigned table suffix
func (a RulesTable) WithSuffix(suffix string) *RulesTable {
	return newRulesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRulesTable(schemaName, tableName, alias string) *RulesTable {
	return &RulesTable{
		rulesTable: newRulesTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newRulesTableImpl("", "excluded", ""),
	}
}

func newRulesTableImpl(schemaName, tableName, alias string) rulesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedByColumn   = postgres.StringColumn("created_by")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, CreatedByColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, DescriptionColumn, CreatedByColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{CreatedAtColumn}
	)

	return rulesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		CreatedBy:   CreatedByColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
