services:
  app:
    build:
      context: ./app
    env_file:
      - ./.env
    volumes:
      - sources:/sources
      - ~/.aws:/root/.aws
    tty: true
    networks:
      - traefik-public
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      - "traefik.http.routers.api-router.entrypoints=websecure"
      - "traefik.http.routers.api-router.rule=Host(`supportocol.dev.hick-r.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api-router.tls=true"
      - "traefik.http.routers.api-router.tls.certresolver=myresolver"
      - "traefik.http.routers.api-router.service=api-svc"
      - "traefik.http.routers.api-router.priority=20"
      - "traefik.http.routers.api-router.middlewares=api-strip"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.services.api-svc.loadbalancer.server.port=9000"

      - "traefik.http.routers.view-router.entrypoints=websecure"
      - "traefik.http.routers.view-router.rule=Host(`supportocol.dev.hick-r.com`)"
      - "traefik.http.routers.view-router.tls=true"
      - "traefik.http.routers.view-router.tls.certresolver=myresolver"
      - "traefik.http.routers.view-router.service=view-svc"
      - "traefik.http.routers.view-router.priority=10"
      - "traefik.http.services.view-svc.loadbalancer.server.port=3000"

  mysql:
    image: mysql:8.4
    command: --performance_schema=0
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=${APP_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

volumes:
  sources:
    external: true
  db_data:

networks:
  traefik-public:
    external: true
  internal:
