services:
  web:
    image: 008544129142.dkr.ecr.ap-northeast-1.amazonaws.com/web-dev:0.0.2
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    ports:
      - ${IP}:80:80
      - ${IP}:443:443
  app:
    build:
      context: ./app
    env_file:
      - ./.env
    volumes:
      - sources:/sources
      - ~/.aws:/root/.aws
    tty: true
  mariadb:
    image: mariadb:11.8
    ports:
      - ${IP}:3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  sources:
    external: true
  mariadb_data:
