openapi: 3.1.0
info:
  title: app-supportocol dialogue api
  version: 1.0.0
components:
  securitySchemes:
    cookie_auth:
      type: apiKey
      in: cookie
      name: auth_token
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          minimum: 100
          maximum: 599
        message:
          type: string
      required:
        - code
        - message
    Id:
      type: string
      format: uuid
    CommentStatus:
      type: string
      enum:
        - active
        - proposed
    DiscussionStatus:
      type: string
      enum:
        - public
        - internal
    PermissionLevel:
      type: string
      enum:
        - everyone
        - authenticated
        - none
    DialogueSettings:
      type: object
      properties:
        commentFrame:
          $ref: "#/components/schemas/CommentFrame"
        commentPermission:
          $ref: "#/components/schemas/PermissionLevel"
        issuePermission:
          $ref: "#/components/schemas/PermissionLevel"
      required:
        - commentFrame
        - commentPermission
        - issuePermission
    CommentFrame:
      type: object
      properties:
        types:
          type: array
          items:
            $ref: "#/components/schemas/CommentType"
        paths:
          type: array
          items:
            $ref: "#/components/schemas/CommentPath"
      required:
        - types
        - paths
    CommentPath:
      type: object
      properties:
        child:
          $ref: "#/components/schemas/CommentType"
        parent:
          $ref: "#/components/schemas/CommentType"
      required:
        - child
        - parent
    DiscussionTheme:
      type: string
      maxLength: 255
    DiscussionConclusion:
      type: string
      maxLength: 1000
    DiscussionPremise:
      type: string
      maxLength: 1000
    DiscussionLanguage:
      type: string
      enum:
        - en
        - ja
    CommentType:
      type: string
      maxLength: 20
    CommentContent:
      type: string
      maxLength: 400
    CommentIssueTitle:
      type: string
      maxLength: 255
    CommentIssueDescription:
      type: string
      maxLength: 1000
    DiscussionSort:
      type: string
      enum:
        - lastCommentedAt
        - favoritesCount
    Page:
      type: integer
      minimum: 1
      default: 1
    PageSize:
      type: integer
      minimum: 1
      maximum: 100
      default: 20
    PaginatedDiscussionSummary:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/DiscussionSummary"
        totalCount:
          type: integer
        page:
          $ref: "#/components/schemas/Page"
        pageSize:
          $ref: "#/components/schemas/PageSize"
      required:
        - items
        - totalCount
        - page
        - pageSize
    DiscussionSummary:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        workspaceId:
          $ref: "#/components/schemas/Id"
        theme:
          $ref: "#/components/schemas/DiscussionTheme"
        status:
          $ref: "#/components/schemas/DiscussionStatus"
        archivedAt:
          oneOf:
            - type: string
              format: date-time
            - type: "null"
        lastCommentedAt:
          type: string
          format: date-time
        commentsCount:
          type: integer
        favoritesCount:
          type: integer
      required:
        - id
        - workspaceId
        - theme
        - status
        - archivedAt
        - lastCommentedAt
        - commentsCount
        - favoritesCount
    Discussion:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        workspaceId:
          $ref: "#/components/schemas/Id"
        theme:
          $ref: "#/components/schemas/DiscussionTheme"
        premise:
          $ref: "#/components/schemas/DiscussionPremise"
        conclusion:
          $ref: "#/components/schemas/DiscussionConclusion"
        language:
          $ref: "#/components/schemas/DiscussionLanguage"
        status:
          $ref: "#/components/schemas/DiscussionStatus"
        archivedAt:
          oneOf:
            - type: string
              format: date-time
            - type: "null"
        dialogueSettings:
          $ref: "#/components/schemas/DialogueSettings"
      required:
        - id
        - workspaceId
        - theme
        - premise
        - conclusion
        - language
        - status
        - archivedAt
        - dialogueSettings
    Comment:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        discussionId:
          $ref: "#/components/schemas/Id"
        parentCommentId:
          oneOf:
            - $ref: "#/components/schemas/Id"
            - type: "null"
        type:
          $ref: "#/components/schemas/CommentType"
        content:
          $ref: "#/components/schemas/CommentContent"
        status:
          $ref: "#/components/schemas/CommentStatus"
        issues:
          type: array
          items:
            $ref: "#/components/schemas/CommentIssue"
        archivedAt:
          oneOf:
            - type: string
              format: date-time
            - type: "null"
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - discussionId
        - parentCommentId
        - type
        - content
        - status
        - issues
        - archivedAt
        - createdAt
    CommentIssue:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        title:
          $ref: "#/components/schemas/CommentIssueTitle"
        description:
          $ref: "#/components/schemas/CommentIssueDescription"
      required:
        - id
        - title
        - description
  parameters:
    workspaceId:
      name: workspaceId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Id"
    discussionId:
      name: discussionId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Id"
    commentId:
      name: commentId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Id"
security:
  - cookie_auth: []
  - {}
paths:
  /v1/dialogue/discussions:
    get:
      description: get public discussions
      parameters:
        - schema:
            $ref: "#/components/schemas/DiscussionSort"
          required: true
          name: sort
          in: query
        - schema:
            $ref: "#/components/schemas/Page"
          required: false
          name: page
          in: query
        - schema:
            $ref: "#/components/schemas/PageSize"
          required: false
          name: pageSize
          in: query
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedDiscussionSummary"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/dialogue/workspaces/{workspaceId}/discussions:
    parameters:
      - $ref: "#/components/parameters/workspaceId"
    get:
      description: get internal discussions for a workspace
      parameters:
        - schema:
            $ref: "#/components/schemas/DiscussionSort"
          required: true
          name: sort
          in: query
        - schema:
            $ref: "#/components/schemas/Page"
          required: false
          name: page
          in: query
        - schema:
            $ref: "#/components/schemas/PageSize"
          required: false
          name: pageSize
          in: query
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedDiscussionSummary"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/dialogue/workspaces/{workspaceId}/discussions/{discussionId}:
    parameters:
      - $ref: "#/components/parameters/workspaceId"
      - $ref: "#/components/parameters/discussionId"
    get:
      description: get discussion
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Discussion"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/dialogue/workspaces/{workspaceId}/discussions/{discussionId}/comments:
    parameters:
      - $ref: "#/components/parameters/workspaceId"
      - $ref: "#/components/parameters/discussionId"
    get:
      description: get comments for a discussion
      parameters:
        - schema:
            type: string
            format: date-time
          required: false
          name: since
          in: query
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: create comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parentCommentId:
                  oneOf:
                    - $ref: "#/components/schemas/Id"
                    - type: "null"
                commentType:
                  $ref: "#/components/schemas/CommentType"
                content:
                  $ref: "#/components/schemas/CommentContent"
              required:
                - parentCommentId
                - commentType
                - content
      responses:
        "201":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/dialogue/workspaces/{workspaceId}/discussions/{discussionId}/comments/{commentId}/issues:
    parameters:
      - $ref: "#/components/parameters/workspaceId"
      - $ref: "#/components/parameters/discussionId"
      - $ref: "#/components/parameters/commentId"
    post:
      description: add issue to comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  $ref: "#/components/schemas/CommentIssueTitle"
                description:
                  $ref: "#/components/schemas/CommentIssueDescription"
              required:
                - title
                - description
      responses:
        "200":
          description: success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        default:
          description: default error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
