// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// V1IdentityErrorsPost implements POST /v1/identity/errors operation.
	//
	// Post an error.
	//
	// POST /v1/identity/errors
	V1IdentityErrorsPost(ctx context.Context, req *V1IdentityErrorsPostReq) error
	// V1IdentityGooglePost implements POST /v1/identity/google operation.
	//
	// Google login.
	//
	// POST /v1/identity/google
	V1IdentityGooglePost(ctx context.Context, req *GoogleLoginRequest) error
	// V1IdentityLoginPost implements POST /v1/identity/login operation.
	//
	// Login with email and password.
	//
	// POST /v1/identity/login
	V1IdentityLoginPost(ctx context.Context, req *LoginWithEmailRequest) error
	// V1IdentityLogoutPost implements POST /v1/identity/logout operation.
	//
	// Logout.
	//
	// POST /v1/identity/logout
	V1IdentityLogoutPost(ctx context.Context) error
	// V1IdentityMeDelete implements DELETE /v1/identity/me operation.
	//
	// Delete current user account.
	//
	// DELETE /v1/identity/me
	V1IdentityMeDelete(ctx context.Context) error
	// V1IdentityMeGet implements GET /v1/identity/me operation.
	//
	// Get current user.
	//
	// GET /v1/identity/me
	V1IdentityMeGet(ctx context.Context) (*User, error)
	// V1IdentityResendVerifyEmailPost implements POST /v1/identity/resend-verify-email operation.
	//
	// Resend verification email.
	//
	// POST /v1/identity/resend-verify-email
	V1IdentityResendVerifyEmailPost(ctx context.Context, req *ResendVerifyEmailRequest) error
	// V1IdentitySignupPost implements POST /v1/identity/signup operation.
	//
	// Signup with email and password.
	//
	// POST /v1/identity/signup
	V1IdentitySignupPost(ctx context.Context, req *SignupWithEmailRequest) error
	// V1IdentityVerifyEmailPost implements POST /v1/identity/verify-email operation.
	//
	// Verify email address.
	//
	// POST /v1/identity/verify-email
	V1IdentityVerifyEmailPost(ctx context.Context, req *VerifyEmailRequest) error
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
