// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// IdentityErrorsPost implements POST /identity/errors operation.
//
// Post an error.
//
// POST /identity/errors
func (UnimplementedHandler) IdentityErrorsPost(ctx context.Context, req *IdentityErrorsPostReq) error {
	return ht.ErrNotImplemented
}

// IdentityGooglePost implements POST /identity/google operation.
//
// Google login.
//
// POST /identity/google
func (UnimplementedHandler) IdentityGooglePost(ctx context.Context, req *GoogleLoginRequest) error {
	return ht.ErrNotImplemented
}

// IdentityLogoutPost implements POST /identity/logout operation.
//
// Logout.
//
// POST /identity/logout
func (UnimplementedHandler) IdentityLogoutPost(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// IdentityMeGet implements GET /identity/me operation.
//
// Get current user.
//
// GET /identity/me
func (UnimplementedHandler) IdentityMeGet(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
