// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fourbetween/app-supportocol/internal/learning/domain (interfaces: DiscussionRepository,CommentRepository)
//
// Generated by this command:
//
//	mockgen -package domain -destination ./repository_mock.go . DiscussionRepository,CommentRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscussionRepository is a mock of DiscussionRepository interface.
type MockDiscussionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscussionRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscussionRepositoryMockRecorder is the mock recorder for MockDiscussionRepository.
type MockDiscussionRepositoryMockRecorder struct {
	mock *MockDiscussionRepository
}

// NewMockDiscussionRepository creates a new mock instance.
func NewMockDiscussionRepository(ctrl *gomock.Controller) *MockDiscussionRepository {
	mock := &MockDiscussionRepository{ctrl: ctrl}
	mock.recorder = &MockDiscussionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscussionRepository) EXPECT() *MockDiscussionRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDiscussionRepository) Delete(ctx context.Context, discussion *Discussion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, discussion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDiscussionRepositoryMockRecorder) Delete(ctx, discussion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDiscussionRepository)(nil).Delete), ctx, discussion)
}

// List mocks base method.
func (m *MockDiscussionRepository) List(ctx context.Context, createdBy string) ([]*Discussion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, createdBy)
	ret0, _ := ret[0].([]*Discussion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDiscussionRepositoryMockRecorder) List(ctx, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiscussionRepository)(nil).List), ctx, createdBy)
}

// Load mocks base method.
func (m *MockDiscussionRepository) Load(ctx context.Context, params LoadParams) (*Discussion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, params)
	ret0, _ := ret[0].(*Discussion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockDiscussionRepositoryMockRecorder) Load(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockDiscussionRepository)(nil).Load), ctx, params)
}

// Save mocks base method.
func (m *MockDiscussionRepository) Save(ctx context.Context, discussion *Discussion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, discussion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDiscussionRepositoryMockRecorder) Save(ctx, discussion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDiscussionRepository)(nil).Save), ctx, discussion)
}

// MockCommentRepository is a mock of CommentRepository interface.
type MockCommentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepositoryMockRecorder
	isgomock struct{}
}

// MockCommentRepositoryMockRecorder is the mock recorder for MockCommentRepository.
type MockCommentRepositoryMockRecorder struct {
	mock *MockCommentRepository
}

// NewMockCommentRepository creates a new mock instance.
func NewMockCommentRepository(ctrl *gomock.Controller) *MockCommentRepository {
	mock := &MockCommentRepository{ctrl: ctrl}
	mock.recorder = &MockCommentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepository) EXPECT() *MockCommentRepositoryMockRecorder {
	return m.recorder
}

// DeleteComment mocks base method.
func (m *MockCommentRepository) DeleteComment(ctx context.Context, comment *Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentRepositoryMockRecorder) DeleteComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentRepository)(nil).DeleteComment), ctx, comment)
}

// FetchComments mocks base method.
func (m *MockCommentRepository) FetchComments(ctx context.Context, discussionID string) ([]*Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchComments", ctx, discussionID)
	ret0, _ := ret[0].([]*Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchComments indicates an expected call of FetchComments.
func (mr *MockCommentRepositoryMockRecorder) FetchComments(ctx, discussionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchComments", reflect.TypeOf((*MockCommentRepository)(nil).FetchComments), ctx, discussionID)
}

// LoadComment mocks base method.
func (m *MockCommentRepository) LoadComment(ctx context.Context, id string) (*Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadComment", ctx, id)
	ret0, _ := ret[0].(*Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadComment indicates an expected call of LoadComment.
func (mr *MockCommentRepositoryMockRecorder) LoadComment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadComment", reflect.TypeOf((*MockCommentRepository)(nil).LoadComment), ctx, id)
}

// SaveComment mocks base method.
func (m *MockCommentRepository) SaveComment(ctx context.Context, comment *Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveComment", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveComment indicates an expected call of SaveComment.
func (mr *MockCommentRepositoryMockRecorder) SaveComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveComment", reflect.TypeOf((*MockCommentRepository)(nil).SaveComment), ctx, comment)
}
